apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharepoint-connector
  labels:
    app: sharepoint-connector
spec:
  selector:
    matchLabels:
      app: sharepoint-connector
  template:
    metadata:
      labels:
        app: sharepoint-connector
    spec:
      containers:
       - name: sharepoint-connector
         image:  virtuan/sharepoint-connector
         imagePullPolicy: Always
         env:
        
          - name: GRPC_PORT
          value: ""
        
          - name: REST_PORT
          value: ""
        
         ports:
          - containerPort: 8080
      imagePullSecrets:
          - name: virtuanregsecrets