apiVersion: v1
kind: Service
metadata:
  name: sharepoint-connectorsrv
  labels:
    app: sharepoint-connectorsrv
    service: sharepoint-connectorsrv
spec:
  ports:
   - port: 9082
     name: http
     targetPort: 8080
  selector:
    app: sharepoint-connector